### ISSUE TITLE
Stop scratching when user clicked out of the scratchable area ?

### ISSUE THREAD

**Issue by sibor94** [websanova/wScratchPad#21]
Well... If you take a look at the demo plugin, you can see that while you are scratching and you go out of the scratchable area and you release the mouse button. Then you put your mouse on the scratchable area and you can still scratch it. Really hope my explanation is clear to you.

Could you tell me how to avoid it please ?

Thank you very much

**Comment by eposjk** [comment]
Got the same issue and fixed it at eposjk@2d29f11.
Maybe the title of this issue is a little bit misleading: As I understand, the problem is not how to disable scratching completely, but stop scratching when the user moves the mouse pointer outside of the scratchable area.
